### ISSUE TITLE
Issue with Auth URL

### ISSUE THREAD

**Issue by kingbd** [omermina/ETradeApiV1#1]
Bringing up the Auth URL in the browser:  "Due to a logon delay or other issue, your authentication could not be completed at this time. Please try again." Pretty sure it's a problem on the ETrade side as I've tried several API implementations and they all get this same error at the Auth URL. ETrade customer support not responding. They used to have an API support forum but the URL is broken.

**Comment by kingbd** [comment]
Hi yes, using that exact app.config with my consumer key/secret entered for the v1 API, which I received a week ago. Using the console app, entering 1 for authenticate. The page resulting from the auth url is below. When credentials are entered get the "Due to a logon delay or other issue, your authentication could not be completed at this time. Please try again." Strange. Have another support ticket opened with ETrade to make sure nothing wrong with the key. (The get Request Token operation works fine, so pretty sure the key is good)

![untitled](https://user-images.githubusercontent.com/46551098/51701412-43069000-1fc6-11e9-8be6-2a27ace93972.png)

**Comment by omermina** [comment]
Are you using the Nuget package or the Git code?
I am asking that because I had that issue while developing, the request token worked but on the next step calling to request the authorize Url I had a type and put in the oauthTokenSecret instead of oauthToken that did produce a valid Url but got the same error message your receive.

Add RenewToken method yesterday and run again the whole process and it works at my end.


```
public string GetAuthorizeUrl()
        {
            var baseUrl = new Uri(_config.TokenUrl);
            var client = new RestClient(baseUrl)
            {
                Authenticator = OAuth1Authenticator.ForRequestToken(_config.ConsumerKey, _config.ConsumerSecret, "oob")
            };

            var request = new RestRequest("/oauth/request_token");
            var response = client.Execute(request);

            var qs = HttpUtility.ParseQueryString(response.Content);
            var oauthToken = qs["oauth_token"];
            var oauthTokenSecret = qs["oauth_token_secret"];

            _config.OauthToken = oauthToken;
            _config.OauthTokenSecret = oauthTokenSecret;

            var applicationName = qs["application_name"];

            var baseSslUrl = new Uri(_config.AuthorizeUrl);
            var sslClient = new RestClient(baseSslUrl);

            request = new RestRequest("authorize");
            request.AddParameter("key", _config.ConsumerKey);
            request.AddParameter("token", **oauthToken**);


            var url = sslClient.BuildUri(request).ToString();

            return url;
        }
```

**Comment by kingbd** [comment]
ETrade support got back to me. There was a problem on their side with the consumer key and I was issued a new one thanks!

**Comment by omermina** [comment]
Good to hear, I am already using the code with production keys, mainly for reading data for options prices and quotes.

**Comment by pracplayopen** [comment]
[this SO question](https://stackoverflow.com/a/7904228/322676) also deals w/the same error.

It points out there is a discrepency in the etrade api docs...

the [etrade authorize api docs](https://apisb.etrade.com/docs/api/authorization/authorize.html) give two different sets of key names to use... one being the official oauth keys for authorization.   using these key do not work.

oauth_consumer_key	header	yes	The value used by the consumer to identify itself to the service provider.	
oauth_token	header	yes	The consumer’s request token.

in the example they use other keys:

> https://us.etrade.com/e/t/etws/authorize?key=282683cc9e4b8fc81dea6bc687d46758&amp;token=%2FiQRgQCRGPo7Xdk6G8QDSEzX0Jsy6sKNcULcDavAGgU%3D

using *key* and *token* as the key names works to resolve the error: "Due to a logon delay or other issue, your authentication could not be completed at this time. Please try again"
